### ISSUE TITLE
Only the first request works, any subsequent requests fail

### ISSUE THREAD

**Issue by georgeportillo** [discord/cloudflare-sample-app#17]
Any pointers?

<img width="473" alt="Screenshot 2023-06-19 at 5 29 00 PM" src="https://github.com/discord/cloudflare-sample-app/assets/1437282/b11765b3-6158-4a7c-ba30-5e64823b990d">

**Comment by JustinBeckwith** [comment]
Are you seeing anything in your logs?

**Comment by colinloretz** [comment]
@georgeportillo is this still happening? The `r/aww` reddit was being used to get your daily dose of cuteness but they went dark during the Reddit blackout so I was seeing some failures as well.
