### ISSUE TITLE
Interactions URL 

### ISSUE THREAD

**Issue by JacobMGEvans** [discord/cloudflare-sample-app#6]
Based on the error I was getting and another issue in a different repo, if the `/interactions` is required for the URL in the Ngrok section it should be added to the description and screenshot.

GH Issue w/ Docs Reference: https://github.com/BookStackApp/BookStack/issues/2558#issuecomment-1159711852
Ngrok Section: https://discord.com/developers/docs/tutorials/hosting-on-cloudflare-workers#setting-up-ngrok

**Comment by JacobMGEvans** [comment]
Error Message (I tried `/interactions`) 
![image](https://user-images.githubusercontent.com/27247160/211240740-263c3409-d3cb-421d-9ea5-d1f226d2c1a6.png)

What the tunnel looks like: 
![image](https://user-images.githubusercontent.com/27247160/211240799-cc410e3f-dd04-4a15-bd69-84c72fbd4576.png)

**Comment by nzwsch** [comment]
@JacobMGEvans 
Hi, I figured it out. We have to check discord's request using [`verifyKey`](https://github.com/discord/discord-interactions-js).
Here's my sample code.
```typescript
import { InteractionResponseType, verifyKey } from 'discord-interactions';

export interface Env {
  DISCORD_PUBLIC_KEY: string;
}

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    const rawBody = await request.text();
    const signature = request.headers.get('X-Signature-Ed25519');
    const timestamp = request.headers.get('X-Signature-Timestamp');
    const pubKey = env.DISCORD_PUBLIC_KEY;

    if (signature == null || timestamp == null) {
      return new Response('Sorry, you have supplied an invalid key.', {
        status: 403,
      });
    }

    const isValidRequest = verifyKey(rawBody, signature, timestamp, pubKey);

    if (!isValidRequest) {
      return new Response('Bad request signature', {
        status: 401,
      });
    }

    return new Response(JSON.stringify({
      type: InteractionResponseType.PONG,
    }), {
      headers: {
        'content-type': 'application/json;charset=UTF-8',
      },
    });
  },
};
```

**Comment by JacobMGEvans** [comment]
> @JacobMGEvans You may forget [`DISCORD_PUBLIC_KEY`](https://github.com/discord/cloudflare-sample-app/blob/main/src/server.js#L100) using wrangler CLI?

I had not 😅

**Comment by nzwsch** [comment]
@JacobMGEvans 

> What the tunnel looks like: ![image](https://user-images.githubusercontent.com/27247160/211240799-cc410e3f-dd04-4a15-bd69-84c72fbd4576.png)

Could you change interactions endpoint url `https://<NGROK_URL>.ngrok.io/interactions`? You should receive 200 request and 401 requests like below.
![Screenshot from 2023-01-28 08-01-43](https://user-images.githubusercontent.com/67128016/215222175-a5c355f4-607b-42ff-ba2a-6add4bbc7cd8.png)

**Comment by JacobMGEvans** [comment]
> **Error Message (I tried `/interactions`)**
IMAGE
> 
> What the tunnel looks like: IMAGE

@nzwsch

**Comment by JustinBeckwith** [comment]
Greetings!  The cloudflare specific tutorial posts messages directly to `/`, which the getting started tutorial you're looking at does in fact post them to `/interactions`.  They're different code bases, and really you can set up your backend to accept messages on any route.  I just double checked everything in this repo and it's 👍
